# Use the official Python image as the base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt /app/

# Install the required Python packages
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the rest of the application files into the container
COPY . /app/

# Expose the port on which the Flask app will run
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]

docker build -t ami_coding_pari_na:latest .

docker run -p 5000:5000 ami_coding_pari_na:latest